CREATE TABLE expenses (
  id BIGSERIAL PRIMARY KEY,
  date DATE NOT NULL,
  item VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  spent DOUBLE PRECISION NOT NULL,
  spent_by VARCHAR(255) NOT NULL
);
